# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.rand(90).reshape(30,3)
data

array([[0.79866204, 0.28912155, 0.22569015],
       [0.5000286 , 0.17208267, 0.59761752],
       [0.13885377, 0.70857224, 0.55665327],
       [0.87414551, 0.80710558, 0.96454522],
       [0.93953122, 0.84239006, 0.08151364],
       [0.84904191, 0.28694895, 0.95057714],
       [0.16616626, 0.66696547, 0.51180578],
       [0.26085339, 0.30390873, 0.12373069],
       [0.47692433, 0.696488  , 0.65230453],
       [0.82887906, 0.55254547, 0.98668639],
       [0.06652743, 0.59635796, 0.24456154],
       [0.91812044, 0.6510255 , 0.22503531],
       [0.05518601, 0.82843873, 0.27923912],
       [0.94814178, 0.29587785, 0.25207337],
       [0.5121527 , 0.0972785 , 0.850924  ],
       [0.55489024, 0.65833098, 0.90012217],
       [0.59501205, 0.11745274, 0.93669611],
       [0.98179636, 0.0622532 , 0.60256082],
       [0.04682241, 0.2182677 , 0.97281192],
       [0.23619536, 0.10889662, 0.72295659],
       [0.11107181, 0.2419258 , 0.55133488],
       [0.70858836, 0.18273173, 0.37177139],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))

clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.99553566, 0.95171781, 0.36157115],
       [0.25912907, 0.37102788, 0.76176839]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
vq(data, clust_centers)

(array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 1, 1, 1, 1]),
 array([0.70445488, 0.35292675, 0.41288565, 0.63184333, 0.30581246,
        0.62507214, 0.39837476, 0.64156064, 0.40662194, 0.63886759,
        0.59613082, 0.33919171, 0.6954509 , 0.66660483, 0.38328632,
        0.43492472, 0.45576029, 0.80183344, 0.3360791 , 0.26597952,
        0.28787246, 0.62415282, 0.57688949, 0.        , 0.89792406,
        0.37322206, 0.        , 0.49124446, 0.46363961, 0.29936344]))

In [6]:
from scipy.cluster.vq import kmeans

In [7]:
kmeans(data, clust_centers)

(array([[0.90141547, 0.4226127 , 0.27375847],
        [0.39760906, 0.4432577 , 0.69633739]]),
 0.40779321181546274)

In [8]:
kmeans(data, 2)

(array([[0.40178436, 0.44316176, 0.74671917],
        [0.79230358, 0.42693358, 0.2575107 ]]),
 0.4045955228969997)